[package]
name = "api"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = "0.7.4"
commonlib = { git = "https://github.com/toolbisoftware/commonlib-rs" }
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
